### ISSUE TITLE
Migrate tf files to helm for fuchicorp-wordpress

### ISSUE THREAD

**Issue by fsadykov** [fuchicorp/fuchicorp-wordpress#1]
Hello, @fuchicorp/devops ,

Delete tf files to migrate our deployments for the helm. Deployment Service and other tf files should move to helm template folder

https://github.com/fuchicorp/fuchicorp-wordpress/blob/d7511650b655a41df5fb68bb59fc564c74d77620/google_k8s_ingress_deployment.tf#L1

**Comment by leventelibal** [comment]
i am block by nexus docker images i need access for docker images until i block by thanks for your support
